name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-arm:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build application for ARM
      run: pyinstaller --onefile --name jjkiller_arm jjkiller/main.py

    - name: Upload ARM artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: jjkiller_arm
        path: dist/*

  build-intel:
    runs-on: macos-11

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build application for Intel
      run: pyinstaller --onefile --name jjkiller_intel jjkiller/main.py

    - name: Upload Intel artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: jjkiller_intel
        path: dist/*

  combine-binaries:
    runs-on: macos-latest
    needs: [build-arm, build-intel]

    steps:
    - name: Download ARM artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: jjkiller_arm
        path: dist_arm

    - name: Download Intel artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: jjkiller_intel
        path: dist_intel

    - name: Combine binaries using lipo
      run: |
        mkdir -p dist
        lipo -create -output dist/jjkiller dist_arm/jjkiller_arm dist_intel/jjkiller_intel

    - name: Upload universal binary
      uses: actions/upload-artifact@v4.3.3
      with:
        name: jjkiller_universal
        path: dist/jjkiller

    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@v2.0.5
      with:
        files: dist/jjkiller