name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-mac-arm64:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build application for ARM64
      run: pyinstaller --onefile --name jjkiller_darwin_arm64 jjkiller/main.py

    - name: Upload ARM64 artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: jjkiller_darwin_arm64
        path: dist/jjkiller_darwin_arm64

  build-mac-amd64:
    runs-on: macos-11

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build application for AMD64
      run: pyinstaller --onefile --name jjkiller_darwin_amd64 jjkiller/main.py

    - name: Upload AMD64 artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: jjkiller_darwin_amd64
        path: dist/jjkiller_darwin_amd64

  build-linux-amd64:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller
        pip install -r requirements.txt

    - name: Build application for AMD64
      run: pyinstaller --onefile --name jjkiller_linux_amd64 jjkiller/main.py

    - name: Upload AMD64 artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: jjkiller_linux_amd64
        path: dist/jjkiller_linux_amd64

  combine-binaries:
    runs-on: ubuntu-latest
    needs: [build-mac-arm64, build-mac-amd64, build-linux-amd64]

    steps:
    - name: Download Darwing ARM64 artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: jjkiller_darwin_arm64
        path: dist_arm

    - name: Download Darwin AMD64 artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: jjkiller_darwin_amd64
        path: dist_amd64

    - name: Download Linux AMD64 artifact
      uses: actions/download-artifact@v4.1.7
      with:
        name: jjkiller_linux_amd64
        path: dist_amd64

    - name: Create release
      id: create_release
      uses: softprops/action-gh-release@v2.0.5
      with:
        files: |
          dist_arm/jjkiller_darwin_arm64
          dist_amd64/jjkiller_darwin_amd64
          dist_amd64/jjkiller_linux_amd64